### ISSUE TITLE
Terminal color, remove white?

### ISSUE THREAD

**Issue by naquiroz** [pawelgrzybek/gatito-theme#2]
I have a powerine theme on my bash terminal, and when I add the gatito theme, looks fine, but with a lot of white
![image](https://user-images.githubusercontent.com/29825816/43810283-d6c83888-9a84-11e8-9c8a-c963b19c43bf.png)
Is there a way to remove that white-ish layer?
ps: I dont care if it is a little bit hacky

**Comment by pawelgrzybek** [comment]
Hi.

White is a default colour of any text values on Gatito Theme. I see that you use something different than default Bash — like zsh or fish. Unfortunately I am not familiar how they control theming of your command line.

Sorry
