### ISSUE TITLE
Theme does not load anymore

### ISSUE THREAD

**Issue by cideM** [pawelgrzybek/gatito-theme#5]
I think that you might have accidentally introduced a trailing comma in https://github.com/pawelgrzybek/gatito-theme/commit/51e9fd4dce5ba46c91d31db188e009a35098aa8d specifically https://github.com/pawelgrzybek/gatito-theme/blob/master/themes/gatito-theme-color-theme.json#L330

Without that, the theme loads without problems, with it I get `Unable to load file:///Users/yuuki/.vscode-insiders/extensions/pawelgrzybek.gatito-theme-0.2.1/themes/gatito-theme-color-theme.json: Problems parsing JSON theme file: Property name expected, Value expected`

I'm using the latest insiders on the latest MacOS

**Comment by pawelgrzybek** [comment]
Hi.

It is working for me with no issues just like expected on stable version. 

I just removed and re-downloaded it — works like a charm.

**Comment by cideM** [comment]
Then this appears to be an insiders issue. It happens with a lot of themes actually.

**Comment by pawelgrzybek** [comment]
Ufff 😌

It is worth to raise a bug on VSCode repo in this case.

Thanks a lot and have a good day ‼️
