### ISSUE TITLE
Highlight variables not working

### ISSUE THREAD

**Issue by danedavid** [pawelgrzybek/gatito-theme#6]
When I place cursor on a variable, all occurrences of the variable are highlighted in other themes:
![image](https://user-images.githubusercontent.com/19928280/54685753-98ca6500-4b3d-11e9-82ef-1ac27cada36d.png)
...but not in this theme:
![image](https://user-images.githubusercontent.com/19928280/54685771-a67fea80-4b3d-11e9-8f2e-3030f967905c.png)

**Comment by pawelgrzybek** [comment]
Hi.

When it is highlighted (like on your top example) it is working as expected.

<img width="832" alt="Screenshot 2019-03-20 at 16 59 00" src="https://user-images.githubusercontent.com/3697104/54704015-d923e600-4b31-11e9-99d8-94a396cf4b74.png">

**Comment by danedavid** [comment]
@pawelgrzybek It is not working on single click. It does in other themes.
I think what you have shown is by *selecting* the first occurence. But usually when you just place your cursor on the first occurence, all occurences of that variable is highlighted.
My VS Code version is 1.32.3.
